name: Use Secrets in Workflow
on: push
jobs: 
  example:
      runs-on: ubuntu-latest
      steps:
        - name: Print a Secret 
          env:
           API_KEY: ${{ secrets.API_KEY }}
          run: |
             echo"THE API_KEY IS $API_KEY"
